apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-client
  template:
    metadata:
      labels:
        app: mail-client
    spec:
      containers:
        - name: mail-client-app
          image: ilyalisov/mail-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: mail-client-secrets
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: mail-client-secrets
                  key: SPRING_MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mail-client-secrets
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-client-secrets
                  key: SPRING_MAIL_PASSWORD
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: mail-client-configmap
                  key: KAFKA_HOST